# Site settings
title: The Hibernating Grizzly
header-img: img/home-bg.png
email: villicana.i@gmail.com
copyright_name: ivillicana
description: > # this means to ignore newlines until "baseurl:"
  A software developer's journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ivillicana
learn_profile: ivillicana
email_username: villicana.i@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
